name: CI

on:
    push:
        branches: [master]
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    php:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: [ '7.3', '7.4', '8.0' ]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}

            - name: Get Composer Cache Directory
              id: get-composer-cache-dir
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache Composer
              uses: actions/cache@v1
              with:
                  path: ${{ steps.get-composer-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - run: composer validate
              if: always()

            - name: Install composer dependencies
              run: composer install --dev --no-progress --no-suggest --prefer-dist --optimize-autoloader

            - name: Run phpunit tests
              run: vendor/bin/phpunit
              if: always()
